name: Capturar Screenshots iOS

on:
  workflow_dispatch: # Permite rodar manualmente
  push:
    branches: [ main ]

jobs:
  ios-screenshots:
    runs-on: macos-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v3
        with:
          channel: stable
          cache: true

      - name: Criar pasta de screenshots
        run: mkdir -p integration_test/screenshots

      - name: Instalar dependências
        run: flutter pub get

      - name: Instalar CocoaPods (iOS)
        run: |
          cd ios
          pod install
          cd ..

      - name: Executar teste e capturar screenshots
        run: |
          flutter drive \
            --driver=test_driver/integration_test.dart \
            --target=integration/login_test.dart \
            -d "iPhone 15 Pro"
        continue-on-error: true

      - name: Upload das screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-ios
          path: integration_test/screenshots/